export function pathToType(path: string) {
	if (path.startsWith("Weapons/Missiles/")) return "Medium+Weapon+Missile";
	switch (path) {
		case "Vehicles/FA-26B":
		case "Vehicles/SEVTF":
		case "Vehicles/VTOL4":
		case "Vehicles/EF-24":
		case "Vehicles/T-55":
			return "Medium+Air+FixedWing";
		case "Vehicles/AH-94":
			return "Medium+Air+Rotorcraft";
		case "Units/Allied/ABomberAI":
			return "Heavy+Air+FixedWing";
		case "Units/Enemy/AEW-50":
			return "Heavy+Air+FixedWing";
		case "Units/Enemy/AIUCAV":
			return "Light+Air+FixedWing";
		case "Units/Allied/AlliedAAShip":
			return "Sea+Watercraft+AircraftCarrier";
		case "Units/Allied/AlliedCarrier":
			return "Sea+Watercraft+AircraftCarrier";
		case "Units/Allied/AlliedCarrier_OLD":
			return "Sea+Watercraft+AircraftCarrier";
		case "Units/Allied/alliedCylinderTent":
			return "Static+Ground+Building";
		case "Units/Allied/AlliedEWRadar":
			return "Static+Ground+AntiAircraft";
		case "Units/Allied/alliedMBT1":
			return "Ground+Heavy+Armor+Vehicle+Tank";
		case "Units/Allied/AlliedSoldier":
			return "Ground+Light+Human+Infantry";
		case "Units/Allied/AlliedSoldierMANPAD":
			return "Ground+Light+Human+Infantry+AntiAircraft";
		case "Units/Allied/ARocketTruck":
			return "Ground+Heavy+Armor+Vehicle";
		case "Units/Enemy/Artillery":
			return "Ground+Heavy+Armor+Vehicle";
		case "Units/Enemy/ASF-30":
			return "Medium+Air+FixedWing";
		case "Units/Enemy/ASF-33":
			return "Medium+Air+FixedWing";
		case "Units/Enemy/ASF-58":
			return "Medium+Air+FixedWing";
		case "Units/Allied/AV-42CAI":
			return "Medium+Air+FixedWing";
		case "Units/Enemy/bunker1":
			return "Static+Ground+Building";
		case "Units/Allied/bunker2":
			return "Static+Ground+Building";
		case "Units/Enemy/cylinderTent":
			return "Static+Ground+Building";
		case "Units/Enemy/DroneCarrier":
			return "Sea+Watercraft+Warship";
		case "Units/Enemy/DroneGunBoat":
			return "Light+Sea+Watercraft+Warship";
		case "Units/Enemy/DroneGunBoatRocket":
			return "Light+Sea+Watercraft+Warship";
		case "Units/Enemy/DroneMissileCruiser":
			return "Sea+Watercraft+Warship";
		case "Units/Allied/E-4":
			return "Heavy+Air+FixedWing";
		case "Units/Enemy/EBomberAI":
			return "Heavy+Air+FixedWing";
		case "Units/Enemy/EnemyCarrier":
			return "Sea+Watercraft+AircraftCarrier";
		case "Units/Enemy/enemyMBT1":
			return "Ground+Heavy+Armor+Vehicle+Tank";
		case "Units/Enemy/EnemySoldier":
			return "Ground+Light+Human+Infantry";
		case "Units/Enemy/EnemySoldierMANPAD":
			return "Ground+Light+Human+Infantry+AntiAircraft";
		case "Units/Enemy/ERocketTruck":
			return "Ground+Heavy+Armor+Vehicle";
		case "Units/Allied/EscortCruiser":
			return "Sea+Watercraft+Warship";
		case "Units/Enemy/ESuperMissileCruiser":
			return "Sea+Watercraft+Warship";
		case "Units/Allied/F-45A AI":
			return "Medium+Air+FixedWing";
		case "Units/Allied/FA-26A":
			return "Medium+Air+FixedWing";
		case "Units/Allied/FA-26B AI":
			return "Medium+Air+FixedWing";
		case "Units/Enemy/GAV-25":
			return "Medium+Air+FixedWing";
		case "Units/Enemy/IRAPC":
			return "Ground+Heavy+Armor+Vehicle+AntiAircraft";
		case "Units/Allied/KC-49":
			return "Heavy+Air+FixedWing";
		case "Units/Enemy/MAD-4Launcher":
			return "Ground+Medium+AntiAircraft+Vehicle";
		case "Units/Enemy/MAD-4Radar":
			return "Ground+Medium+AntiAircraft+Vehicle";
		case "Units/Enemy/MineBoat":
			return "Light+Sea+Watercraft+Warship";
		case "Units/Allied/MQ-31":
			return "Light+Air+FixedWing";
		case "Units/Allied/PatRadarTrailer":
			return "Static+Ground+AntiAircraft";
		case "Units/Allied/PatriotLauncher":
			return "Static+Ground+AntiAircraft";
		case "Units/Allied/PhallanxTruck":
			return "Static+Ground+AntiAircraft";
		case "Units/Enemy/SAAW":
			return "Ground+Heavy+Armor+Vehicle+AntiAircraft";
		case "Units/Enemy/SamBattery1":
			return "Static+Ground+AntiAircraft";
		case "Units/Enemy/SamFCR":
			return "Static+Ground+AntiAircraft";
		case "Units/Enemy/SamFCR2":
			return "Static+Ground+AntiAircraft";
		case "Units/Allied/SRADTruck":
			return "Ground+Heavy+Armor+Vehicle+AntiAircraft";
		case "Units/Enemy/staticAAA-20x2":
			return "Static+Ground+AntiAircraft";
		case "Units/Allied/staticCIWS":
			return "Static+Ground+AntiAircraft";

		default:
			return null;
	}
}
